version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:jdk17-preview
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins-compose
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  postgres-db:
    image: postgres
    container_name: postgres-compose
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - 5432:5432